name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET core
            uses: actions/setup-dotnet@v4
            with:
               dotnet-version: '8.x'
               cache: true
               cache-dependency-path: ./src/**/packages.lock.json
          
          - name: Build and Test .NET core project
            run: |
               dotnet restore ./src/Todo.Api.sln   
               dotnet build --no-restore ./src/Todo.Api.sln
               dotnet test --no-build ./src/Todo.Api.sln --no-restore --configuration Release --logger trx --results-directory "TestResults"

          - uses: actions/upload-artifact@v2
            with:
               name: dotnet-test-results
               path: "TestResults"
          
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                 node-version: '20'
                 cache: npm
                 cache-dependency-path: ./src/web
          
          - name: Install dependencies
            working-directory: ./src/web
            run: |
               npm install
               npm run build